[workspace]
members = [
    "halo2-ecc-circuit-lib",
    "halo2-snark-aggregator",
    "halo2-snark-aggregator-api",
    "halo2-snark-aggregator-circuit",
    "halo2-snark-aggregator-solidity",
]

[patch.crates-io]
# This fork makes bitvec 0.20.x work with funty 1.1 and funty 1.2.  Without
# this fork, bitvec 0.20.x is incompatible with funty 1.2, which we depend on,
# and leads to a compilation error.  This can be removed once the upstream PR
# is resolved: https://github.com/bitvecto-rs/bitvec/pull/141
bitvec = { git = "https://github.com/ed255/bitvec.git", rev = "5cfc5fa8496c66872d21905e677120fc3e79693c" }