[package]
name = "halo2-snark-aggregator-circuit"
version = "0.1.0"
edition = "2021"
authors = ["zhangjunyu <junyu92@gmail.com>"]

[dependencies]
clap = { version = "3.1.11", features = ["derive"] }
halo2-ecc-circuit-lib = { path = "../halo2-ecc-circuit-lib" }
halo2-snark-aggregator-api = { path = "../halo2-snark-aggregator-api" }
halo2_proofs = { git = "https://github.com/junyu0312/halo2", rev = "4112958c7fa980b331897fd030a329095f418ff9", default-features = true }
log = "0.4.17"
pairing_bn256 = { git = "https://github.com/appliedzkp/pairing", tag = "v0.1.1" }
rand = "0.8"
rand_core = "0.6.3"
rand_pcg = "0.3.1"
serde_json = "1.0"
rayon = "1.5.2"

[features]
default = ["halo2"]
blake2b = []
halo2 = []
plonk = []
