[package]
name = "halo2-snark-aggregator-solidity"
version = "0.1.0"
edition = "2021"
authors = ["zhangjunyu <junyu92@gmail.com>"]

[dependencies]
halo2_proofs = { git = "https://github.com/junyu0312/halo2", rev = "35fae8cfb75052516aeaceddbd16e3f1c54edad2", default-features = true }
# halo2-ecc-circuit-lib = { path = "../halo2-ecc-circuit-lib" }
halo2_ecc = { git = "https://github.com/jonathanpwang/halo2-ecc", branch = "scroll-aggregator" }
halo2-snark-aggregator-api = { path = "../halo2-snark-aggregator-api" }
halo2-snark-aggregator-circuit = { path = "../halo2-snark-aggregator-circuit" }
log = "0.4.17"
num-bigint = { version = "0.4", features = ["rand"] }
pairing_bn256 = { git = "https://github.com/appliedzkp/pairing", tag = "v0.1.1" }
sha3 = "0.10.1"
tera = "1.15.0"
